oss:
  region: ""
  bucketName: ""
  directory: ""
  accessKey: ""
  secretKey: ""
  customUrl: ""

db:
  dsn: ""
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 50 # 打开数据库连接的最大数量

refresh:
  workerNum: 40

query:
  workerNum: 40
  distance: 5